<a href="https://colab.research.google.com/github/garima-pachori/Python-for-Data-Science/blob/main/Complete_numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4]
print(l)

[1, 2, 3, 4]


**Advantages of numpy over lists**


*   **Efficiency**: NumPy is faster for numerical operations due to C implementation.
*   **Vectorization**: Allows element-wise operations without loops.
*  **Broadcasting**: Handles operations on arrays of different shapes.
*  **Library Ecosystem**: Foundation for many scientific libraries.
*   **Multidimensional Arrays**: Supports multi-dimensional data structures.
*   **Math Functions**: Provides comprehensive mathematical functions.
*  **Parallel Processing**: Utilizes multi-core CPUs for speed.
*   **Cross-Language Integration**: Interfaces with C, C++, and Fortran.
*   **Memory Efficiency**: Stores homogeneous data more efficiently.
*   **Ease of Use**: Simplifies common scientific computing tasks.







In [ ]:
print("1 D array")
a=np.array([1,2,3,4])
print(a)

print("2 D array")
b=np.array([[1,2,3,4],[4,5,6,7]])
print(b)

print("3 D array")
c=np.array([[[1,2,3,4],[4,5,6,7],[8,19,20,21]]])
print(c)

1 D array
[1 2 3 4]
2 D array
[[1 2 3 4]
 [4 5 6 7]]
3 D array
[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 8 19 20 21]]]


In [ ]:
type(a) #n dimentional array of numpy type

numpy.ndarray

size = tells about the number of elements in the array

In [ ]:
print(a.size)
print(b.size)
print(c.size)

4
8
12


shape=(rows,columns)

In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 4)
(1, 3, 4)


dtype= type of data type present in the array

In [ ]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


transpose of a matrix can be done in numpy using

*   arr.transpose()



In [ ]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
arr.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

For creating an empty array in numpy using dummy entries

np.empty((rows,colums), dtype)

In [28]:
np.empty((4,4),dtype=int)

array([[     98174096567598,                   0, 7311066427795573289,
        7018969345223652210],
       [3972238893807658862, 6133938014827197230, 7598242681305851251,
        8241904473059648097],
       [7957697953151197285, 7021244194802001255, 2314861394247640174,
        7020303014056697888],
       [7308895158389664103, 7023201308319639840, 2338606692303926137,
        7594873701694008949]])

In [29]:
np.empty((4,4),dtype=float)

array([[4.85044477e-310, 0.00000000e+000, 6.62438493e+265,
        1.96680888e+243],
       [1.26004864e+232, 1.01341102e+242, 6.01347002e-154,
        5.76720550e+228],
       [5.04620658e+180, 2.25538747e+276, 6.45598388e+170,
        2.43567338e-152],
       [2.48021224e+180, 5.98742040e+247, 9.08367229e+223,
        2.66123004e-258]])



---


The **np.ones()** function generates an array filled with the value 1. In this case, you are creating an array with six elements, and all elements will have the value 1.


---



In [32]:
x=np.ones(6)
print(x)
x

[1. 1. 1. 1. 1. 1.]


array([1., 1., 1., 1., 1., 1.])

In [35]:
y=np.ones((4,4))
print(y)

y

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
y=np.ones((4,4), dtype=int)
print(y)

y

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [36]:
x=np.zeros(6)
print(x)
x

[0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0.])

In [38]:
y=np.zeros((4,4))
print(y)
y

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
y=np.zeros((4,4), dtype=int)
print(y)
y

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
y=np.zeros((4,4), dtype=str)
print(y)


y=np.zeros((4,4), dtype=bool)
print(y)
y

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])



---


The ***np.arange()*** function is used to create an array of evenly spaced values within a specified range.

np.arange(start,end,step)


---



In [46]:
a=np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [49]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]




---


The ***reshape()*** method in NumPy is used to change the shape of an existing array without changing its data. It allows you to specify the dimensions (shape) you want for the resulting array as long as the total number of elements remains the same.

***arr.reshape((rows,columns))***


---



In [51]:
a=a.reshape((3,3)) #only 9 elements must be there in that array then
print(a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
