<a href="https://colab.research.google.com/github/garima-pachori/Python-for-Data-Science/blob/main/Complete_numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4]
print(l)

[1, 2, 3, 4]


**Advantages of numpy over lists**


*   **Efficiency**: NumPy is faster for numerical operations due to C implementation.
*   **Vectorization**: Allows element-wise operations without loops.
*  **Broadcasting**: Handles operations on arrays of different shapes.
*  **Library Ecosystem**: Foundation for many scientific libraries.
*   **Multidimensional Arrays**: Supports multi-dimensional data structures.
*   **Math Functions**: Provides comprehensive mathematical functions.
*  **Parallel Processing**: Utilizes multi-core CPUs for speed.
*   **Cross-Language Integration**: Interfaces with C, C++, and Fortran.
*   **Memory Efficiency**: Stores homogeneous data more efficiently.
*   **Ease of Use**: Simplifies common scientific computing tasks.







In [ ]:
print("1 D array")
a=np.array([1,2,3,4])
print(a)

print("2 D array")
b=np.array([[1,2,3,4],[4,5,6,7]])
print(b)

print("3 D array")
c=np.array([[[1,2,3,4],[4,5,6,7],[8,19,20,21]]])
print(c)

1 D array
[1 2 3 4]
2 D array
[[1 2 3 4]
 [4 5 6 7]]
3 D array
[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 8 19 20 21]]]


In [ ]:
type(a) #n dimentional array of numpy type

numpy.ndarray

size = tells about the number of elements in the array

In [ ]:
print(a.size)
print(b.size)
print(c.size)

4
8
12


shape=(rows,columns)

In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 4)
(1, 3, 4)


dtype= type of data type present in the array

In [ ]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


transpose of a matrix can be done in numpy using

*   arr.transpose()



In [ ]:
arr=np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
arr.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])